/* Generated by Yosys 0.60+95 (git sha1 991e70489, clang++ 18.1.8 -fPIC -O3) */

module counter(clk, rst, q);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  INVX1 _10_ (
    .A(rst),
    .Y(_00_)
  );
  INVX1 _11_ (
    .A(q[0]),
    .Y(_06_)
  );
  NAND2X1 _12_ (
    .A(q[0]),
    .B(q[1]),
    .Y(_04_)
  );
  XOR2X1 _13_ (
    .A(q[0]),
    .B(q[1]),
    .Y(_07_)
  );
  NAND3X1 _14_ (
    .A(q[0]),
    .B(q[1]),
    .C(q[2]),
    .Y(_05_)
  );
  XNOR2X1 _15_ (
    .A(q[2]),
    .B(_04_),
    .Y(_08_)
  );
  XNOR2X1 _16_ (
    .A(q[3]),
    .B(_05_),
    .Y(_09_)
  );
  INVX1 _17_ (
    .A(rst),
    .Y(_01_)
  );
  INVX1 _18_ (
    .A(rst),
    .Y(_02_)
  );
  INVX1 _19_ (
    .A(rst),
    .Y(_03_)
  );
  DFFSR _20_ (
    .CLK(clk),
    .D(_06_),
    .Q(q[0]),
    .R(_00_),
    .S(1'b1)
  );
  DFFSR _21_ (
    .CLK(clk),
    .D(_07_),
    .Q(q[1]),
    .R(_01_),
    .S(1'b1)
  );
  DFFSR _22_ (
    .CLK(clk),
    .D(_08_),
    .Q(q[2]),
    .R(_02_),
    .S(1'b1)
  );
  DFFSR _23_ (
    .CLK(clk),
    .D(_09_),
    .Q(q[3]),
    .R(_03_),
    .S(1'b1)
  );
endmodule
