/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-02 21:47:28
*/

module counter
(
  clk,
  rst,
  q,
  _20_,
  \_20_.d ,
  _21_,
  \_21_.d ,
  _22_,
  \_22_.d ,
  _23_,
  \_23_.d 
);

  input _20_;
  output \_20_.d ;
  input _21_;
  output \_21_.d ;
  input _22_;
  output \_22_.d ;
  input _23_;
  output \_23_.d ;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;

  INVX1
  _10_
  (
    .A(rst),
    .Y(_00_)
  );


  INVX1
  _11_
  (
    .A(q[0]),
    .Y(_06_)
  );


  NAND2X1
  _12_
  (
    .A(q[0]),
    .B(q[1]),
    .Y(_04_)
  );


  XOR2X1
  _13_
  (
    .A(q[0]),
    .B(q[1]),
    .Y(_07_)
  );


  NAND3X1
  _14_
  (
    .A(q[0]),
    .B(q[1]),
    .C(q[2]),
    .Y(_05_)
  );


  XNOR2X1
  _15_
  (
    .A(q[2]),
    .B(_04_),
    .Y(_08_)
  );


  XNOR2X1
  _16_
  (
    .A(q[3]),
    .B(_05_),
    .Y(_09_)
  );


  INVX1
  _17_
  (
    .A(rst),
    .Y(_01_)
  );


  INVX1
  _18_
  (
    .A(rst),
    .Y(_02_)
  );


  INVX1
  _19_
  (
    .A(rst),
    .Y(_03_)
  );

  assign q[0] = _20_;
  assign \_20_.d  = _06_;
  assign q[1] = _21_;
  assign \_21_.d  = _07_;
  assign q[2] = _22_;
  assign \_22_.d  = _08_;
  assign q[3] = _23_;
  assign \_23_.d  = _09_;

endmodule
